### ISSUE TITLE
C++ Seemingly not linking in Eclipse Neon with WPILib for 2017

### ISSUE THREAD

**Issue by icecube45** [JacisNonsense/Pathfinder#6] opened 2017-01-10 02:41 UTC
Hi!
This library looks exactly like what I've been looking for, my only issue is that it doesn't appear to link in eclipse neon.

My project outputs the errors of
```
..\src/Robot.cpp:58: undefined reference to `d2r(double)'
..\src/Robot.cpp:66: undefined reference to `pf_fit_hermite_cubic(Waypoint, Waypoint, Spline*)'
..\src/Robot.cpp:66: undefined reference to `pf_fit_hermite_cubic(Waypoint, Waypoint, Spline*)'
..\src/Robot.cpp:66: undefined reference to `pathfinder_prepare(Waypoint*, int, void (*)(Waypoint,Waypoint,Spline*), int, double, double, double, double, TrajectoryCandidate*)'
..\src/Robot.cpp:71: undefined reference to `pathfinder_generate(TrajectoryCandidate*, Segment*)'
..\src/Robot.cpp:77: undefined reference to `pathfinder_modify_tank(Segment*, int, Segment*, Segment*, double)'
```

I'm pretty sure I'm linking it correctly, the lib folder is in my search paths for libraries, and the pathfinder library is on the top of my list.

Any help would be greatly appreciated.

**Comment by JacisNonsense** [comment] 2017-01-11 01:58
Are you using the 2017 Plugins?

**Comment by icecube45** [comment] 2017-01-11 02:01
Indeed I am

**Comment by JacisNonsense** [comment] 2017-01-11 07:13
Try putting the pathfinder libraries in `~/wpilib/user/java`, the same place the SRX libraries are stored (if you installed them).

**Comment by icecube45** [comment] 2017-01-11 23:42
I'm using cpp, but putting the includes and library under the cpp section of the wpilib folder (where the third party libraries are) results in no change.

**Comment by JacisNonsense** [comment] 2017-01-16 01:23
I've found the issue. It turns out WPILib doesn't link `.a` files, only `.so` files. Hold tight and I'll build a `.so` version for you to include

**Comment by JacisNonsense** [comment] 2017-01-16 01:33
Head to the [releases](https://github.com/JacisNonsense/Pathfinder/releases) and download the C++ fix, export this into your `~/wpilib/user/cpp` folder and it should work.

**Comment by icecube45** [comment] 2017-01-16 08:18
Great! I'll try it out tomorrow and report back

**Comment by Sloth7** [comment] 2017-01-28 21:07
Did you get this working?  We are having problems linking the .so following the instructions in the wiki.

**Comment by Kython89** [comment] 2017-01-28 21:18
Working with @Sloth7 on this.  The .so file in the most recent release is only 27KB.  Is this correct?  It seems small.

**Comment by JacisNonsense** [comment] 2017-01-29 06:30
@Kython89 Yes, this is correct. Pathfinder doesn't have any dependencies so the binary is fairly small. 27KB seems nominal

@Sloth7 don't use the Wiki instructions for this. Put the `.so` library under `~/wpilib/user/cpp/lib` and the header files under `~/wpilib/user/cpp/include`

**Comment by CaptainGeneric** [comment] 2017-01-29 07:18
My team has been working on getting this integrated to a 2017 C++ Command Base project and have been running into the same issue.

I believe the issue is due to name mangling between C and C++.
The errors were resolved by adding `extern "C"` around all of the includes in `pathfinder.h`. ([gist](https://gist.github.com/CaptainGeneric/c7398acac2c6db92ac2c3dae74091a95))
A clean of the project after adding `extern` allows the project to build successfully.

I have pulled in both the most recent release with the .so and the previous release with the .a binaries at different times.  Both seem to work just fine as far as compiling goes.  CTRE, SF2, etc. all seem to have .a binaries and can be pulled in just fine.

Thoughts?

**Comment by JacisNonsense** [comment] 2017-01-29 07:39
@CaptainGeneric Pathfinder is designed to be a C library, that can be imported into C++ projects.  Does it build successfully if, in your robot program, you use
```c
extern "C" #include "pathfinder.h"
```
instead of
```c
#include "pathfinder.h"
```

**Comment by CaptainGeneric** [comment] 2017-01-29 08:27
Yeah, I wasn't a fan of modifying the header file to get the project to compile.  That's definitely not the resolution.

I did try your suggestion (and a few other things) and didn't have any luck by changing the way the robot project includes the library.  I'll try to pick this back up tomorrow to see if I can figure out anything else.

Let me know if you have any other ideas.  I would be happy to give them a shot.

**Comment by JacisNonsense** [comment] 2017-01-29 08:29
Hmm, if adding `extern "C"` seems to fix it in the pathfinder.h file, I'll put in an `ifdef __cplusplus` for it. Hold tight, I'll work on something soon

**Comment by JacisNonsense** [comment] 2017-01-29 09:34
There's now a fix up that allows Pathfinder to be included with WPILib C++ projects. Get the [release here](https://github.com/JacisNonsense/Pathfinder/releases/tag/1.5-extern) and extract it to `~/wpilib/user/cpp`. This should close this issue, if there's anything else related to this issue please reopen it or create a new one

**Closed by JacisNonsense** 2017-01-29 09:34 UTC

**Comment by Kython89** [comment] 2017-01-29 23:02
@JacisNonsense The latest release you provided works great and we can now link.
